import type { Metadata } from "next";
import { Providers } from "@/providers";
import { fonts } from "@/config/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={fonts.spaceMono.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
